version: "3.9"
services:
  gateway-api:
    build: .
    restart: always
    ports:
     - 8082:8082
    environment:
      - ACCOMMODATION_API_GRPC_ADDRESS=accommodation-api
      - USER_API_GRPC_ADDRESS=user-api
      - RESERVATION_API_GRPC_ADDRESS=reservation-api

networks:
  default:
    name: local-env_default
