version: "3.9"
services:
  gateway-api:
    build: .
    restart: always
    container_name: gateway
    volumes:
      - type: volume
        source: local-env_shared
        target: /home
    ports:
     - 8082:8082
    environment:
      - ACCOMMODATION_API_GRPC_ADDRESS=accommodation-api
      - USER_API_GRPC_ADDRESS=user-api
      - RESERVATION_API_GRPC_ADDRESS=reservation-api

networks:
  default:
    name: local-env_default

volumes:
  local-env_shared:
    external: true